# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'AsyncImageLoading' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AsyncImageLoading
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 3.1'



  target 'AsyncImageLoadingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AsyncImageLoadingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
